server:
  port: 8081
spring:
  application:
    name: front-end
  thymeleaf:
    mode: HTML5
    cache: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: front-end
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2