server:
  port: 8081

spring:
  application:
    name: front-end
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: front-end
    preferIpAddress: false
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2