server:
  port: 8081
spring:
  application:
    name: front-end
  template:
    cache:false

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 2