#This file will be replaced with a docker orchestrator
version: '3'
services:
  eureka-server:
    build: eureka-server/
    ports:
      - '8761:8761'
  hello-world:
    build: hello-world/
    ports:
      - '8080:8080'