server:
  port: 8083
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://mongo:27017
      database: test
      repositories:
        #        TODO: this is deprecated, use something else.
        enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: post-service
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2