server:
  port: 8085
spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb://rs0:27017,rs1:27017,rs2:27017,rs3:27017
      database: test
      repositories:
        #        TODO: this is deprecated, use something else.
        enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: search-service
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2