logging:
  level:
    org:
      springframework:
        data: debug

server:
  port: 8085
spring:
  application:
    name: search-service

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 2