version: '3.7'

services:
  eureka-server:
    image: arcilli/demetria-eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - my-overlay
  user-service:
    image: arcilli/demetria-user-service:2.0-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - my-overlay
  post-service:
    image: arcilli/demetria-post-service:2.0-SNAPSHOT
    ports:
      - "8083:8083"
    networks:
      - my-overlay
  front-end:
    image: arcilli/demetria-front-end:1.0-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - my-overlay
  friendship-relation:
    image: arcilli/demetria-friendship-relation-service:1.0-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - my-overlay
  # TODO: add volumes
  rs1:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
  rs2:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
  rs3:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
  rs-setup:
    image: arcilli/demetria-mongo-replicas:1.0-SNAPSHOT
    networks:
      - my-overlay
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
  orient-db:
    image: orientdb:latest
    ports:
      - "2424:2424"
      - "2480:24"
networks:
  my-overlay:
    driver: overlay