spring:
  application:
    name: user-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://eureka-server:8761/eureka
      #      Local development
      defaultZone: http://localhost:8761/eureka