server:
  port: 8080
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://rs0:27017,rs1:27017,rs2:27017,rs3:27017
      database: test
      host: mongo
      port: 27017
      repositories:
        type: auto

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: user-service
    preferIpAddress: false
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2