version: '3.7'

services:
  user-service:
    image: arcilli/demetria-user-service:2.4
    ports:
      - "8080:8080"
    networks:
      - my-overlay
  post-service:
    image: arcilli/demetria-post-service:2.4
    ports:
      - "8083:8083"
    networks:
      - my-overlay
  front-end:
    image: arcilli/demetria-front-end:2.4
    ports:
      - "8081:8081"
    networks:
      - my-overlay
  friendship-relation:
    image: arcilli/demetria-friendship-relation-service:2.4
    ports:
      - "8082:8082"
    networks:
      - my-overlay
  search-service:
    image: arcilli/demetria-search-service:2.4
    ports:
      - "8085:8085"
    networks:
      - my-overlay
  rs1:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
    volumes:
      - mongo-rs1:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
  rs2:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
    volumes:
      - mongo-rs2:/data/db
  rs3:
    image: mongo
    command: mongod --replSet "rs0"
    networks:
      - my-overlay
    volumes:
      - mongo-rs3:/data/db
  rs-setup:
    image: arcilli/demetria-mongo-replicas:2.4
    networks:
      - my-overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
  orient-db:
    image: orientdb:latest
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
    volumes:
      - orient-config:/orientdb/config
      - orient-databases:/orientdb/databases
      - orient-backup:/orientdb/backup
    networks:
      - my-overlay
  orient-db-initial-setup:
    image: arcilli/demetria-orient-init-setup:2.4
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    networks:
      - my-overlay

networks:
  my-overlay:
    driver: overlay

volumes:
  mongo-rs1:
    external: false
  mongo-rs2:
    external: false
  mongo-rs3:
    external: false
  orient-config:
    external: false
  orient-databases:
    external: false
  orient-backup:
    external: false
