server:
  port: 8082

spring:
  application:
    name: friendship-relation-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    hostname: friendship-relation-service
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 2