server:
  port: 8082
spring:
  application:
    name: friendship-relation

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 2
    serviceUrl:
      defaultZone: http://localhost:8761/eureka