spring:
  application:
    name: friendship-relation-service

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #            defaultZone: http://eureka-server:8761/eureka
      #      Local development
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082